# This is for dev
version: '3'
services:
  sto2-wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8443:8443"
      - "8082:8080"
    command: --https-port 8443
    volumes:
      - $PWD/wiremock-docker/stubs:/home/wiremock
  sto2-rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15673:15672"
      - "5673:5672"
  sto2-postgres:
    image: postgres:10.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sto2-indicator
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sto2_indicator
  sto2-adminer:
    image: adminer:4.6.3-standalone
    ports:
      - "8081:8080"
