# This is for dev
version: '3'
services:
  sto2-wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8443:8443"
      - "8082:8080"
    command: --https-port 8443
    volumes:
      - $PWD/wiremock-docker/stubs:/home/wiremock
  sto2-rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15673:15672"
      - "5673:5672"
  sto2-mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: stoxygen_indicator
      MYSQL_USER: sto2-indicator
      MYSQL_PASSWORD: 1234560
  sto2-adminer:
    image: adminer:4.6.3-standalone
    ports:
      - "8081:8080"
  sto2-redis:
    image: redis:5.0.1-stretch
    ports:
      - "6379:6379"




